library(dplyr)
library(lubridate)
data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data <- filter(data, Date == "1/2/2007" | Date == "2/2/2007")
data$DateandTime <- paste(data$Date, data$Time)
data$DateandTime <- dmy_hms(data$DateandTime)
png(file = "plot3.png")
plot(data$DateandTime, data$Sub_metering_1, type = "n",xlab = "", ylab = "Energy sub metering", yaxp = c(0,30,3))
points(data$DateandTime, data$Sub_metering_1, type = "l", col = "black")
points(data$DateandTime, data$Sub_metering_2, type = "l", col = "red")
points(data$DateandTime, data$Sub_metering_3, type = "l", col = "blue")
legend("topright",lty = 1, seg.len = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()