library(dplyr)
library(lubridate)
data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data <- filter(data, Date == "1/2/2007" | Date == "2/2/2007")
data$DateandTime <- paste(data$Date, data$Time)
data$DateandTime <- dmy_hms(data$DateandTime)
png(file = "plot4.png")
par(mar = c(4,4,2,2), mfrow = c(2,2))
plot(data$DateandTime, data$Global_active_power, type = "l",xlab = "", ylab = "Global Active Power", yaxp = c(0,6,3))
plot(data$DateandTime, data$Voltage, type = "l",xlab = "datetime", ylab = "Voltage", yaxp = c(234,246,6))
plot(data$DateandTime, data$Sub_metering_1, type = "n",xlab = "", ylab = "Energy sub metering", yaxp = c(0,30,3))
points(data$DateandTime, data$Sub_metering_1, type = "l", col = "black")
points(data$DateandTime, data$Sub_metering_2, type = "l", col = "red")
points(data$DateandTime, data$Sub_metering_3, type = "l", col = "blue")
legend("topright",lty = 1, seg.len = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty = "n")
plot(data$DateandTime, data$Global_reactive_power, type = "l",xlab = "datetime", ylab = "Global_reactive_power", yaxp = c(0.0,0.5,5))
dev.off()