library(dplyr)
library(lubridate)
data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data <- filter(data, Date == "1/2/2007" | Date == "2/2/2007")
data$DateandTime <- paste(data$Date, data$Time)
data$DateandTime <- dmy_hms(data$DateandTime)
plot(data$DateandTime, data$Global_active_power, type = "l",xlab = "", ylab = "Global Active Power (kilowatts)", yaxp = c(0,6,3))
dev.copy(png, file = "plot2.png")
dev.off()