library(dplyr)
library(lubridate)
data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data <- filter(data, Date == "1/2/2007" | Date == "2/2/2007")
hist(data$Global_active_power, xlab = "Global Active Power (kilowatts)", col = "red", main = "Global Active Power", xaxp = c(0,6,3), yaxp = c(0,1200,6))
dev.copy(png, file = "plot1.png")
dev.off()